package com.project.assignment.utils.exceptions;

public enum ApiErrorMessageKeyEnum {
	U_BOOK_ISBN,
	INCORRECT_RESULT_SIZE_DATA_ACCESS,
	NULL_POINTER_EXCEPTION,
	RUN_TIME_EXCEPTION,
	DATABASE_CONSTRAINT_VIOLATION,
	MODEL_PARAMETER_TYPE_MISS_MATCH,
	GENERAL_ERROR,
	ACCESS_IS_DENIED,
	MEDIA_TYPE_NOT_SUPPORTED,
	MEDIA_TYPE_NOT_ACCEPTED,
	METHOD_NOT_ALLOWED,
	PATH_PARAMETER_TYPE_MISS_MATCH,
	JDBC_CONNECTON_ERROR,
	REFRENCE_ID_NOT_FOUND;

}
